### PR TITLE
Respect user specified widget text rule

### PR DESCRIPTION
**Pull request by tlongren**
Applies to issue #3:
This CSS rule is not respecting what the user specified. It should be removed:
.widget.widget-text img, .widget.widget_text img { width: 100%; }

### CODE REVIEW

**Comment by jojoee** [comment]
Thank you @tlongren, I gonna check it tomorrow.

**Comment by jojoee** [comment]
checking...

**Comment by jojoee** [comment]
@tlongren do you have https://wordpress.org/ account?
I would like to add you as the contributor.

**Comment by tlongren** [comment]
@jojoee WordPress username is tlongren.

**Pull request merged**
